### ISSUE TITLE
Enable customization form action buttons.

### ISSUE THREAD

**Issue by yyanwang** [Talend/react-talend-forms#20]
For now we have 2 fixed form action buttons - Submit and Cancel.
I propose to let user customize form actions via the Form component's children. A default submit button will be rendered if no children provided to the Form component.

**Comment by yyanwang** [comment]
One more question, I would like to have a Reset button in Form.
when I tried to add type='reset' to current Cancel button in Form, it won't reset the field value.

**Comment by frassinier** [comment]
Yes for customizatuon, feel free to open à PR with all your needs.

Why do you need a reset button? I will try BTW

**Comment by yyanwang** [comment]
Thanks. 
It's the requirement, so when user edit an item and then want to restore the intial values...

**Comment by talend-glorieux** [comment]
@yyanwang Great job on the pull request. 
I'm not sure the reset button is a requirement for every forms. Would it make sense to add one if a "resettable" prop is passed to the Form?

**Comment by yyanwang** [comment]
@talend-glorieux Hi, yes I agree that it's not a common case to have a reset button for every form, I just didn't figure it out how to reset the form with react-talend-form or react-jsonschema-form...

**Comment by talend-glorieux** [comment]
I'm not sure it's actually implemented in [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form). I'll double check but if it's the case it might be a good idea to raise an issues on the project.

**Comment by talend-glorieux** [comment]
Yep I can confirm that it's not implemented. I'll raise an issue.

**Comment by talend-glorieux** [comment]
Open as https://github.com/mozilla-services/react-jsonschema-form/issues/360

**Comment by yyanwang** [comment]
thanks Geoffroy! :smiley:

**Comment by talend-glorieux** [comment]
Hey @yyanwang, there is an answer on the [issue I created](https://github.com/mozilla-services/react-jsonschema-form/issues/360).
To summarize, when it comes to resetting the forms, they prefer to make it by resetting the formData from the wrapper instead of adding the functionality to the library.

**Comment by yyanwang** [comment]
OK, thanks for the information Geoffroy @talend-glorieux
I will check how to make this work from my end.

**Comment by acateland** [comment]
guess we can close this issue ?
