### ISSUE TITLE
Add inline form support

### ISSUE THREAD

**Issue by talend-glorieux** [Talend/react-talend-forms#40]
There is a use case for inline forms. It looks like there isn't any support for it on [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form). Will need to handle it directly on react-talend-forms.

**Comment by jmfrancois** [comment]
should look like this but with material design
![screen shot 2016-11-21 at 11 30 25](https://cloud.githubusercontent.com/assets/19857479/20479291/f582cb78-afdd-11e6-9d3f-d4606a6f734d.png)

source: http://getbootstrap.com/css/#forms-inline

**Comment by talend-glorieux** [comment]
This issue was moved to Talend/ui#36
