### ISSUE TITLE
Errors messages should be comprehensible by user

### ISSUE THREAD

**Issue by jlamiel** [Talend/react-talend-forms#47]
Example :   
"default": "gs://temp",
"pattern": "^gs://(.*?([^/]+))$"
right now the message is : does not match pattern "^gs://(.*?([^/]+))$"

**Comment by talend-glorieux** [comment]
Will be handled once https://github.com/mozilla-services/react-jsonschema-form/pull/432 is merged.

**Comment by talend-glorieux** [comment]
Adding https://github.com/mozilla-services/react-jsonschema-form/issues/155 as a reference,

**Comment by talend-glorieux** [comment]
This issue was moved to Talend/ui#34
