### ISSUE TITLE
Prefix import

### ISSUE THREAD

**Issue by frassinier** [Talend/react-talend-forms#5]
It could be cool to prefix import names such as [BCheckbox](https://github.com/Talend/react-bootstrap-forms/blob/7635373eb0ec3b47bbc22c74a5ce36269e3df827/src/Checkbox.js#L5-L5) to quickly identify who provides each React Component.

**Comment by talend-glorieux** [comment]
In most cases you won't need to import anything else than the `Form` component. But I could understand the need for prefixes.

**Comment by frassinier** [comment]
Fix by #13
