### ISSUE TITLE
Create widget for key-value parameters

### ISSUE THREAD

**Issue by jlamiel** [Talend/react-talend-forms#50]
For advanced properties in lot of our components and cluster definitions we will need key-value parameters. a key in a technical name of a properties, this key have default value.

The key field is a list but the use should be able to enter manually a custom properties that is not in the list

![image](https://cloud.githubusercontent.com/assets/4313434/21057085/7c634fa6-be38-11e6-9606-aa3645cc129a.png)

**Comment by mmaillart** [comment]
can I experience a preview of this widget in live mode ? : )

**Comment by talend-glorieux** [comment]
@mmaillart You'll see it [there](https://talend.github.io/react-talend-forms/) once merged.
