### ISSUE TITLE
Create a list widget for filter component

### ISSUE THREAD

**Issue by jlamiel** [Talend/react-talend-forms#55]
Component filter will need to handle list of complex elements.

Here is the (not up-to-date) mockup from Marc.  

![image](https://cloud.githubusercontent.com/assets/4313434/21226187/a9767900-c2d4-11e6-8e8a-1b23af5ab8ba.png)

The description of the components itself can be found here : https://jira.talendforge.org/browse/TFD-168

**Comment by talend-glorieux** [comment]
This issue was moved to Talend/ui#31
